package com.nmontytskyi.monitoring.server.entity;

import com.nmontytskyi.monitoring.model.HealthStatus;
import jakarta.persistence.*;
import lombok.*;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;

/**
 * JPA entity representing a microservice registered in the monitoring system.
 *
 * <p>A service registers itself on startup (via the starter) by sending a POST request
 * to {@code /api/services}. After that the server begins collecting its metrics via
 * the pull scheduler and accepts push snapshots from its embedded aspect.
 *
 * <p>Maps to the {@code registered_services} table.
 */
@Entity
@Table(name = "registered_services")
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class RegisteredServiceEntity {

    /** Surrogate primary key, generated by the database sequence. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Logical service name, unique across the monitoring system.
     * Taken from {@code @MonitoredMicroservice(name = "...")}.
     */
    @Column(nullable = false, unique = true, length = 128)
    private String name;

    /** Host or IP address where the service is running. */
    @Column(nullable = false)
    private String host;

    /** Port the service is listening on. */
    @Column(nullable = false)
    private int port;

    /**
     * Full URL to the service's {@code /actuator} endpoint.
     * Used by the pull scheduler. Example: {@code http://localhost:8081/actuator}.
     */
    @Column(name = "actuator_url")
    private String actuatorUrl;

    /**
     * Base HTTP URL of the service.
     * Example: {@code http://localhost:8081}.
     */
    @Column(name = "base_url")
    private String baseUrl;

    /**
     * Current health status of the service.
     * Updated after every pull cycle and after evaluating push snapshots.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 16)
    @Builder.Default
    private HealthStatus status = HealthStatus.UNKNOWN;

    /** Timestamp when the service first registered with the monitoring server. */
    @CreatedDate
    @Column(name = "registered_at", nullable = false, updatable = false)
    private LocalDateTime registeredAt;

    /**
     * Timestamp of the last successful contact with this service
     * (either a successful pull or a received push snapshot).
     */
    @Column(name = "last_seen_at")
    private LocalDateTime lastSeenAt;

    /**
     * SLA contract for this service.
     * Stored in a separate {@code sla_definitions} table (1:1 relationship).
     */
    @OneToOne(mappedBy = "service", cascade = CascadeType.ALL,
              fetch = FetchType.LAZY, orphanRemoval = true)
    private SlaDefinitionEntity slaDefinition;
}
