package com.nmontytskyi.monitoring.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * Describes a microservice registered in the monitoring system.
 *
 * <p>Created automatically at service startup via {@code ServiceRegistrationBean}
 * from the {@code monitoring-spring-boot-starter} and sent to the
 * {@code monitoring-server} through the REST API.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ServiceInfo {

    /**
     * Unique service identifier (UUID, generated by the server upon registration).
     */
    private String id;

    /**
     * Logical service name. Taken from the {@code name} attribute of the
     * {@code @MonitoredMicroservice} annotation, or from {@code spring.application.name}.
     */
    private String name;

    /**
     * Host or IP address where the service is running.
     */
    private String host;

    /**
     * Port the service is listening on.
     */
    private int port;

    /**
     * Full URL to the {@code /actuator} endpoint of the service.
     * Used by {@code monitoring-server} for pull-based metrics collection.
     * Example: {@code "http://localhost:8081/actuator"}.
     */
    private String actuatorUrl;

    /**
     * Base URL of the service for HTTP health checks.
     * Example: {@code "http://localhost:8081"}.
     */
    private String baseUrl;

    /**
     * SLA parameters for this service. If not specified,
     * default values from {@link SlaDefinition#defaults()} are used.
     */
    private SlaDefinition sla;

    /**
     * Timestamp when the service was registered in the monitoring system.
     */
    private LocalDateTime registeredAt;
}
