server:
  port: 8081

spring:
  application:
    name: inventory-service

monitoring:
  server-url: ${MONITORING_SERVER_URL:http://localhost:8080}
  actuator-url: ${MONITORING_ACTUATOR_URL:http://localhost:8081/actuator}
  base-url: ${MONITORING_BASE_URL:http://localhost:8081}
