server:
  port: 8081

spring:
  application:
    name: inventory-service

monitoring:
  server:
    url: http://localhost:8080
  service:
    base-url: http://localhost:8081
    actuator-url: http://localhost:8081/actuator
