server:
  port: 8085

spring:
  application:
    name: user-service

monitoring:
  server-url: ${MONITORING_SERVER_URL:http://localhost:8080}
  actuator-url: ${MONITORING_ACTUATOR_URL:http://localhost:8085/actuator}
  base-url: ${MONITORING_BASE_URL:http://localhost:8085}
